version: '3.8'

services:
  cinema_db:
    image: postgres:16.3
    volumes:
      - ./cinema-service.sql:/docker-entrypoint-initdb.d/cinema.sql
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: cinema_db

    ports:
      - 5432:5432
