spring:
  profiles:
    active: dev
  rabbitmq:
    username: admin
    password: admin
    listener:
      direct:
        retry:
          enabled: true
          initial-interval: 1000ms
          max-interval: 10000ms
      simple:
        default-requeue-rejected: false
  config:
    import:
      - "aws-secretsmanager:cinema-service/secrets/"

    location: us-east-2
  liquibase:
    enabled: true
    change-log: classpath:/config/liquibase/changelog.xml
  web:
    locale: en_US

server:
  port: 8081

cinema:
  max-session-hours: 5
  min-session-minutes: 10
  image-provider: "simple-storage"
  movie-image-upload-directory: "src/main/resources/static/images/movies/"
  s3-bucket-name: "cinema-service-movie-images"
  aws-region: "US_EAST_2"
  image-generator: "openai"