spring:
  profiles:
    active: dev
  rabbitmq:
    username: admin
    password: admin
    listener:
      direct:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000ms
          max-interval: 10000ms
      simple:
        default-requeue-rejected: false
  liquibase:
    enabled: true
    change-log: classpath:/config/liquibase/changelog.xml

server:
  port: 8081

cinema:
  max-session-hours: 5
  min-session-minutes: 10
